apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: proxy
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set,
  # but we are specifying the selector here to
  # demonstrate its usage.
  selector:
    matchLabels:
      tier: proxy
  template:
    metadata:
      labels:
        tier: proxy
    spec:
      containers:
      - name: proxy
        image: smothiki/quantum:5
        ports:
        - containerPort: 6000
        command:
          - start
          - proxy
